# Generated by Django 5.1.7 on 2025-03-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
